export type { 
  SafetyStatus,
  PlanVariant,
  CapacityBand,
  SymptomScore010,
  RedFlagKey,
  TodayCheckInInput,
  TreatmentTimelineInput,
  UserSafetyProfile,
  UserPreferences,
  UserProfileInput,
  TrendInputs,
  Exercise,
  WorkoutDose,
  WorkoutExercise,
  WorkoutBlock,
  Explainability,
  TodayPlanOutput,
  GenerateTodayPlanInput
} from "../../shared/types/decisionEngine";
